@startuml


Node "<<Java Runtime>>" as JR{
  Node "<<Java Development Kit>>" as JDK{
    Node "Game Editor" as GE{


    }
    Node "Compiler" as C{


    }
  }
  Node "Game Engine" as GE2{


  }
}

GE .. C
@enduml