name: Java CI with Maven
on:
  push:
    branches: ["Git-Hub-Action"]
    paths-ignore: -'docs/**'
  pull_request:
    branches: ["main"]
    paths-ignore: -'docs/**'
  workflow_dispatch:

jobs:
  Set-Up:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
  Build:
    needs: Set-Up
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn compile
  Test:
    runs-on: windows-latest
    needs: [Set-Up, Build]
    steps:
      - uses: actions/checkout@v3
      - name: Test with Maven
        run: mvn test
